name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # SemVer tags

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm -r build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # publish each public package in order (filter avoids private)
          pnpm -r --filter "./packages/*" publish --access public --no-git-checks || true

      - name: Build UI artifacts
        run: pnpm --filter @ax/ui build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/ui/dist/**
          generate_release_notes: true
